/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Common } from './Common';
import {
    CommonFromJSON,
    CommonFromJSONTyped,
    CommonToJSON,
} from './Common';
import type { EnglishAddress } from './EnglishAddress';
import {
    EnglishAddressFromJSON,
    EnglishAddressFromJSONTyped,
    EnglishAddressToJSON,
} from './EnglishAddress';

/**
 * 
 * @export
 * @interface AddrEngResponseResults
 */
export interface AddrEngResponseResults {
    /**
     * 
     * @type {Common}
     * @memberof AddrEngResponseResults
     */
    common?: Common;
    /**
     * 
     * @type {Array<EnglishAddress>}
     * @memberof AddrEngResponseResults
     */
    juso?: Array<EnglishAddress> | null;
}

/**
 * Check if a given object implements the AddrEngResponseResults interface.
 */
export function instanceOfAddrEngResponseResults(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddrEngResponseResultsFromJSON(json: any): AddrEngResponseResults {
    return AddrEngResponseResultsFromJSONTyped(json, false);
}

export function AddrEngResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddrEngResponseResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'common': !exists(json, 'common') ? undefined : CommonFromJSON(json['common']),
        'juso': !exists(json, 'juso') ? undefined : (json['juso'] === null ? null : (json['juso'] as Array<any>).map(EnglishAddressFromJSON)),
    };
}

export function AddrEngResponseResultsToJSON(value?: AddrEngResponseResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'common': CommonToJSON(value.common),
        'juso': value.juso === undefined ? undefined : (value.juso === null ? null : (value.juso as Array<any>).map(EnglishAddressToJSON)),
    };
}

