/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 전체 도로명주소
     * @type {string}
     * @memberof Address
     */
    roadAddr: string;
    /**
     * 도로명주소(참고항목 제외)
     * @type {string}
     * @memberof Address
     */
    roadAddrPart1: string;
    /**
     * 도로명주소 참고항목
     * @type {string}
     * @memberof Address
     */
    roadAddrPart2?: string;
    /**
     * 지번주소
     * @type {string}
     * @memberof Address
     */
    jibunAddr: string;
    /**
     * 도로명주소(영문)
     * @type {string}
     * @memberof Address
     */
    engAddr: string;
    /**
     * 우편번호
     * @type {string}
     * @memberof Address
     */
    zipNo: string;
    /**
     * 행정구역코드
     * @type {string}
     * @memberof Address
     */
    admCd: string;
    /**
     * 도로명코드
     * @type {string}
     * @memberof Address
     */
    rnMgtSn: string;
    /**
     * 건물관리번호
     * @type {string}
     * @memberof Address
     */
    bdMgtSn: string;
    /**
     * 상세건물명
     * @type {string}
     * @memberof Address
     */
    detBdNmList?: string;
    /**
     * 건물명
     * @type {string}
     * @memberof Address
     */
    bdNm?: string;
    /**
     * 공동주택여부
     * * `1` : 공동주택
     * * `0` : 비공동주택
     * @type {string}
     * @memberof Address
     */
    bdKdcd: AddressBdKdcdEnum;
    /**
     * 시도명
     * @type {string}
     * @memberof Address
     */
    siNm: string;
    /**
     * 시군구명
     * @type {string}
     * @memberof Address
     */
    sggNm: string;
    /**
     * 읍면동명
     * @type {string}
     * @memberof Address
     */
    emdNm: string;
    /**
     * 법정리명
     * @type {string}
     * @memberof Address
     */
    liNm?: string;
    /**
     * 도로명
     * @type {string}
     * @memberof Address
     */
    rn: string;
    /**
     * 지하여부
     * * `0` : 지상
     * * `1` : 지하)
     * @type {string}
     * @memberof Address
     */
    udrtYn: AddressUdrtYnEnum;
    /**
     * 건물본번
     * @type {string}
     * @memberof Address
     */
    buldMnnm: string;
    /**
     * 건물부번
     * @type {string}
     * @memberof Address
     */
    buldSlno: string;
    /**
     * 산여부
     * * `0` : 대지
     * * `1` : 산
     * @type {string}
     * @memberof Address
     */
    mtYn: AddressMtYnEnum;
    /**
     * 지번본번(번지)
     * @type {string}
     * @memberof Address
     */
    lnbrMnnm: string;
    /**
     * 지번부번(호)
     * @type {string}
     * @memberof Address
     */
    lnbrSlno: string;
    /**
     * 읍면동일련번호
     * @type {string}
     * @memberof Address
     */
    emdNo: string;
    /**
     * 변동이력여부 (\* 2020년12월8일 추가된 항목)
     * * `0`: 현행 주소정보
     * * `1`: 요청변수의 keyword(검색어)가 변동된 주소정보에서 검색된 정보)
     * @type {string}
     * @memberof Address
     */
    hstryYn?: AddressHstryYnEnum;
    /**
     * 관련지번 (\* 2020년12월8일 추가된 항목)
     * @type {string}
     * @memberof Address
     */
    relJibun?: string;
    /**
     * 관할주민센터 (\* 2020년12월8일 추가된 항목)
     * 
     * ※ 참고정보이며, 실제와 다를 수 있습니다.
     * @type {string}
     * @memberof Address
     */
    hemdNm?: string;
}


/**
 * @export
 */
export const AddressBdKdcdEnum = {
    _0: '0',
    _1: '1'
} as const;
export type AddressBdKdcdEnum = typeof AddressBdKdcdEnum[keyof typeof AddressBdKdcdEnum];

/**
 * @export
 */
export const AddressUdrtYnEnum = {
    _0: '0',
    _1: '1'
} as const;
export type AddressUdrtYnEnum = typeof AddressUdrtYnEnum[keyof typeof AddressUdrtYnEnum];

/**
 * @export
 */
export const AddressMtYnEnum = {
    _0: '0',
    _1: '1'
} as const;
export type AddressMtYnEnum = typeof AddressMtYnEnum[keyof typeof AddressMtYnEnum];

/**
 * @export
 */
export const AddressHstryYnEnum = {
    _0: '0',
    _1: '1'
} as const;
export type AddressHstryYnEnum = typeof AddressHstryYnEnum[keyof typeof AddressHstryYnEnum];


/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "roadAddr" in value;
    isInstance = isInstance && "roadAddrPart1" in value;
    isInstance = isInstance && "jibunAddr" in value;
    isInstance = isInstance && "engAddr" in value;
    isInstance = isInstance && "zipNo" in value;
    isInstance = isInstance && "admCd" in value;
    isInstance = isInstance && "rnMgtSn" in value;
    isInstance = isInstance && "bdMgtSn" in value;
    isInstance = isInstance && "bdKdcd" in value;
    isInstance = isInstance && "siNm" in value;
    isInstance = isInstance && "sggNm" in value;
    isInstance = isInstance && "emdNm" in value;
    isInstance = isInstance && "rn" in value;
    isInstance = isInstance && "udrtYn" in value;
    isInstance = isInstance && "buldMnnm" in value;
    isInstance = isInstance && "buldSlno" in value;
    isInstance = isInstance && "mtYn" in value;
    isInstance = isInstance && "lnbrMnnm" in value;
    isInstance = isInstance && "lnbrSlno" in value;
    isInstance = isInstance && "emdNo" in value;

    return isInstance;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roadAddr': json['roadAddr'],
        'roadAddrPart1': json['roadAddrPart1'],
        'roadAddrPart2': !exists(json, 'roadAddrPart2') ? undefined : json['roadAddrPart2'],
        'jibunAddr': json['jibunAddr'],
        'engAddr': json['engAddr'],
        'zipNo': json['zipNo'],
        'admCd': json['admCd'],
        'rnMgtSn': json['rnMgtSn'],
        'bdMgtSn': json['bdMgtSn'],
        'detBdNmList': !exists(json, 'detBdNmList') ? undefined : json['detBdNmList'],
        'bdNm': !exists(json, 'bdNm') ? undefined : json['bdNm'],
        'bdKdcd': json['bdKdcd'],
        'siNm': json['siNm'],
        'sggNm': json['sggNm'],
        'emdNm': json['emdNm'],
        'liNm': !exists(json, 'liNm') ? undefined : json['liNm'],
        'rn': json['rn'],
        'udrtYn': json['udrtYn'],
        'buldMnnm': json['buldMnnm'],
        'buldSlno': json['buldSlno'],
        'mtYn': json['mtYn'],
        'lnbrMnnm': json['lnbrMnnm'],
        'lnbrSlno': json['lnbrSlno'],
        'emdNo': json['emdNo'],
        'hstryYn': !exists(json, 'hstryYn') ? undefined : json['hstryYn'],
        'relJibun': !exists(json, 'relJibun') ? undefined : json['relJibun'],
        'hemdNm': !exists(json, 'hemdNm') ? undefined : json['hemdNm'],
    };
}

export function AddressToJSON(value?: Address | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roadAddr': value.roadAddr,
        'roadAddrPart1': value.roadAddrPart1,
        'roadAddrPart2': value.roadAddrPart2,
        'jibunAddr': value.jibunAddr,
        'engAddr': value.engAddr,
        'zipNo': value.zipNo,
        'admCd': value.admCd,
        'rnMgtSn': value.rnMgtSn,
        'bdMgtSn': value.bdMgtSn,
        'detBdNmList': value.detBdNmList,
        'bdNm': value.bdNm,
        'bdKdcd': value.bdKdcd,
        'siNm': value.siNm,
        'sggNm': value.sggNm,
        'emdNm': value.emdNm,
        'liNm': value.liNm,
        'rn': value.rn,
        'udrtYn': value.udrtYn,
        'buldMnnm': value.buldMnnm,
        'buldSlno': value.buldSlno,
        'mtYn': value.mtYn,
        'lnbrMnnm': value.lnbrMnnm,
        'lnbrSlno': value.lnbrSlno,
        'emdNo': value.emdNo,
        'hstryYn': value.hstryYn,
        'relJibun': value.relJibun,
        'hemdNm': value.hemdNm,
    };
}

