/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddrCoordResponseResults } from './AddrCoordResponseResults';
import {
    AddrCoordResponseResultsFromJSON,
    AddrCoordResponseResultsFromJSONTyped,
    AddrCoordResponseResultsToJSON,
} from './AddrCoordResponseResults';

/**
 * 
 * @export
 * @interface AddrCoordResponse
 */
export interface AddrCoordResponse {
    /**
     * 
     * @type {AddrCoordResponseResults}
     * @memberof AddrCoordResponse
     */
    results?: AddrCoordResponseResults;
}

/**
 * Check if a given object implements the AddrCoordResponse interface.
 */
export function instanceOfAddrCoordResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddrCoordResponseFromJSON(json: any): AddrCoordResponse {
    return AddrCoordResponseFromJSONTyped(json, false);
}

export function AddrCoordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddrCoordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : AddrCoordResponseResultsFromJSON(json['results']),
    };
}

export function AddrCoordResponseToJSON(value?: AddrCoordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': AddrCoordResponseResultsToJSON(value.results),
    };
}

