/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddrLinkResults } from './AddrLinkResults';
import {
    AddrLinkResultsFromJSON,
    AddrLinkResultsFromJSONTyped,
    AddrLinkResultsToJSON,
} from './AddrLinkResults';

/**
 * 
 * @export
 * @interface AddrLinkResponse
 */
export interface AddrLinkResponse {
    /**
     * 
     * @type {AddrLinkResults}
     * @memberof AddrLinkResponse
     */
    results: AddrLinkResults;
}

/**
 * Check if a given object implements the AddrLinkResponse interface.
 */
export function instanceOfAddrLinkResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function AddrLinkResponseFromJSON(json: any): AddrLinkResponse {
    return AddrLinkResponseFromJSONTyped(json, false);
}

export function AddrLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddrLinkResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': AddrLinkResultsFromJSON(json['results']),
    };
}

export function AddrLinkResponseToJSON(value?: AddrLinkResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': AddrLinkResultsToJSON(value.results),
    };
}

