/* tslint:disable */
/* eslint-disable */
/**
 * 한국수출입은행 오픈 API
 * 한국수출입은행이 보유한 공공데이터를 제공받아 누구나 직접 응용프로그램과 서비스개발 등에 활용할 수 있습니다.
 *
 * The version of the OpenAPI document: 2022.08.10
 * Contact: h.lee@koreaexim.go.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InterestFailed,
    instanceOfInterestFailed,
    InterestFailedFromJSON,
    InterestFailedFromJSONTyped,
    InterestFailedToJSON,
} from './InterestFailed';
import {
    InterestSuccess,
    instanceOfInterestSuccess,
    InterestSuccessFromJSON,
    InterestSuccessFromJSONTyped,
    InterestSuccessToJSON,
} from './InterestSuccess';

/**
 * @type InterestResponseInner
 * 
 * @export
 */
export type InterestResponseInner = InterestFailed | InterestSuccess;

export function InterestResponseInnerFromJSON(json: any): InterestResponseInner {
    return InterestResponseInnerFromJSONTyped(json, false);
}

export function InterestResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...InterestFailedFromJSONTyped(json, true), ...InterestSuccessFromJSONTyped(json, true) };
}

export function InterestResponseInnerToJSON(value?: InterestResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfInterestFailed(value)) {
        return InterestFailedToJSON(value as InterestFailed);
    }
    if (instanceOfInterestSuccess(value)) {
        return InterestSuccessToJSON(value as InterestSuccess);
    }

    return {};
}

