/* tslint:disable */
/* eslint-disable */
/**
 * 한국수출입은행 오픈 API
 * 한국수출입은행이 보유한 공공데이터를 제공받아 누구나 직접 응용프로그램과 서비스개발 등에 활용할 수 있습니다.
 *
 * The version of the OpenAPI document: 2022.08.10
 * Contact: h.lee@koreaexim.go.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterestFailed
 */
export interface InterestFailed {
    /**
     * 조회 결과
     * | 결과코드 | 설명 |
     * | --- | --- |
     * | 2 | DATA코드 오류 |
     * | 3 | 인증코드 오류 |
     * | 4 | 일일제한횟수 마감 |
     * @type {number}
     * @memberof InterestFailed
     */
    result: InterestFailedResultEnum;
    /**
     * 대출기간
     * @type {string}
     * @memberof InterestFailed
     */
    sflnIntrcNm: string | null;
    /**
     * 고정기준금리
     * @type {string}
     * @memberof InterestFailed
     */
    intR: string | null;
}

/**
 * 조회 결과
 * | 결과코드 | 설명 |
 * | --- | --- |
 * | 2 | DATA코드 오류 |
 * | 3 | 인증코드 오류 |
 * | 4 | 일일제한횟수 마감 |
 */
export type InterestFailedResultEnum =
    2|
    3|
    4

const InterestFailedResultEnumValues = [
    2,
    3,
    4,
]

export function isInterestFailedResultEnum(value: any): value is InterestFailedResultEnum {
    return InterestFailedResultEnumValues.indexOf(value as unknown as InterestFailedResultEnum) !== -1
}



/**
 * Check if a given object implements the InterestFailed interface.
 */
export function instanceOfInterestFailed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "sflnIntrcNm" in value;
    isInstance = isInstance && "intR" in value;

    return isInstance;
}

export function InterestFailedFromJSON(json: any): InterestFailed {
    return InterestFailedFromJSONTyped(json, false);
}

export function InterestFailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestFailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!exists(json, 'result')) {
        return json;
    }
    if (
        !isInterestFailedResultEnum(json['result'])
        && json['result'] !== undefined
    ) {
        return json;
    }
    return {
        
        'result': json['result'],
        'sflnIntrcNm': json['sfln_intrc_nm'],
        'intR': json['int_r'],
    };
}

export function InterestFailedToJSON(value?: InterestFailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'sfln_intrc_nm': value.sflnIntrcNm,
        'int_r': value.intR,
    };
}

