/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Common } from './Common';
import {
    CommonFromJSON,
    CommonFromJSONTyped,
    CommonToJSON,
} from './Common';
import type { DetailAddress } from './DetailAddress';
import {
    DetailAddressFromJSON,
    DetailAddressFromJSONTyped,
    DetailAddressToJSON,
} from './DetailAddress';

/**
 * 
 * @export
 * @interface AddrDetailResults
 */
export interface AddrDetailResults {
    /**
     * 
     * @type {Common}
     * @memberof AddrDetailResults
     */
    common: Common;
    /**
     * 
     * @type {Array<DetailAddress>}
     * @memberof AddrDetailResults
     */
    juso: Array<DetailAddress> | null;
}

/**
 * Check if a given object implements the AddrDetailResults interface.
 */
export function instanceOfAddrDetailResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "common" in value;
    isInstance = isInstance && "juso" in value;

    return isInstance;
}

export function AddrDetailResultsFromJSON(json: any): AddrDetailResults {
    return AddrDetailResultsFromJSONTyped(json, false);
}

export function AddrDetailResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddrDetailResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'common': CommonFromJSON(json['common']),
        'juso': (json['juso'] === null ? null : (json['juso'] as Array<any>).map(DetailAddressFromJSON)),
    };
}

export function AddrDetailResultsToJSON(value?: AddrDetailResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'common': CommonToJSON(value.common),
        'juso': (value.juso === null ? null : (value.juso as Array<any>).map(DetailAddressToJSON)),
    };
}

