/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddrDetailResults } from './AddrDetailResults';
import {
    AddrDetailResultsFromJSON,
    AddrDetailResultsFromJSONTyped,
    AddrDetailResultsToJSON,
} from './AddrDetailResults';

/**
 * 
 * @export
 * @interface AddrDetailResponse
 */
export interface AddrDetailResponse {
    /**
     * 
     * @type {AddrDetailResults}
     * @memberof AddrDetailResponse
     */
    results: AddrDetailResults;
}

/**
 * Check if a given object implements the AddrDetailResponse interface.
 */
export function instanceOfAddrDetailResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function AddrDetailResponseFromJSON(json: any): AddrDetailResponse {
    return AddrDetailResponseFromJSONTyped(json, false);
}

export function AddrDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddrDetailResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': AddrDetailResultsFromJSON(json['results']),
    };
}

export function AddrDetailResponseToJSON(value?: AddrDetailResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': AddrDetailResultsToJSON(value.results),
    };
}

