/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailAddress
 */
export interface DetailAddress {
    /**
     * 행정구역코드
     * @type {string}
     * @memberof DetailAddress
     */
    admCd: string;
    /**
     * 도로명코드
     * @type {string}
     * @memberof DetailAddress
     */
    rnMgtSn: string;
    /**
     * 지하여부
     * * `0` : 지상
     * * `1` : 지하
     * @type {string}
     * @memberof DetailAddress
     */
    udrtYn: DetailAddressUdrtYnEnum;
    /**
     * 건물본번
     * @type {string}
     * @memberof DetailAddress
     */
    buldMnnm: string;
    /**
     * 건물부번
     * @type {string}
     * @memberof DetailAddress
     */
    buldSlno: string;
    /**
     * 동 정보
     * @type {string}
     * @memberof DetailAddress
     */
    dongNm?: string;
    /**
     * 층 정보
     * @type {string}
     * @memberof DetailAddress
     */
    floorNm?: string;
    /**
     * 호 정보
     * @type {string}
     * @memberof DetailAddress
     */
    hoNm?: string;
}

/**
 * 지하여부
 * * `0` : 지상
 * * `1` : 지하
 */
export type DetailAddressUdrtYnEnum =
    '0'|
    '1'

const DetailAddressUdrtYnEnumValues = [
    '0',
    '1',
]

export function isDetailAddressUdrtYnEnum(value: any): value is DetailAddressUdrtYnEnum {
    return DetailAddressUdrtYnEnumValues.indexOf(value as unknown as DetailAddressUdrtYnEnum) !== -1
}



/**
 * Check if a given object implements the DetailAddress interface.
 */
export function instanceOfDetailAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "admCd" in value;
    isInstance = isInstance && "rnMgtSn" in value;
    isInstance = isInstance && "udrtYn" in value;
    isInstance = isInstance && "buldMnnm" in value;
    isInstance = isInstance && "buldSlno" in value;

    return isInstance;
}

export function DetailAddressFromJSON(json: any): DetailAddress {
    return DetailAddressFromJSONTyped(json, false);
}

export function DetailAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!exists(json, 'udrtYn')) {
        return json;
    }
    if (
        !isDetailAddressUdrtYnEnum(json['udrtYn'])
        && json['udrtYn'] !== undefined
    ) {
        return json;
    }
    return {
        
        'admCd': json['admCd'],
        'rnMgtSn': json['rnMgtSn'],
        'udrtYn': json['udrtYn'],
        'buldMnnm': json['buldMnnm'],
        'buldSlno': json['buldSlno'],
        'dongNm': !exists(json, 'dongNm') ? undefined : json['dongNm'],
        'floorNm': !exists(json, 'floorNm') ? undefined : json['floorNm'],
        'hoNm': !exists(json, 'hoNm') ? undefined : json['hoNm'],
    };
}

export function DetailAddressToJSON(value?: DetailAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'admCd': value.admCd,
        'rnMgtSn': value.rnMgtSn,
        'udrtYn': value.udrtYn,
        'buldMnnm': value.buldMnnm,
        'buldSlno': value.buldSlno,
        'dongNm': value.dongNm,
        'floorNm': value.floorNm,
        'hoNm': value.hoNm,
    };
}

