/* tslint:disable */
/* eslint-disable */
/**
 * 공동주택가격정보서비스
 * 공동주택에 대해 매년 공시기준일(1월1일)에 공시한 공동주택 가격정보의 지리데이터에서 생성된 맵 이미지와 도형 및 속성 값을 포함한 피처 집합을 제공하는 공동주택가격정보서비스
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApartHousingPriceAttrResponseApartHousingPrices } from './ApartHousingPriceAttrResponseApartHousingPrices';
import {
    ApartHousingPriceAttrResponseApartHousingPricesFromJSON,
    ApartHousingPriceAttrResponseApartHousingPricesFromJSONTyped,
    ApartHousingPriceAttrResponseApartHousingPricesToJSON,
} from './ApartHousingPriceAttrResponseApartHousingPrices';

/**
 * 
 * @export
 * @interface ApartHousingPriceAttrResponse
 */
export interface ApartHousingPriceAttrResponse {
    /**
     * 
     * @type {ApartHousingPriceAttrResponseApartHousingPrices}
     * @memberof ApartHousingPriceAttrResponse
     */
    apartHousingPrices?: ApartHousingPriceAttrResponseApartHousingPrices;
}

/**
 * Check if a given object implements the ApartHousingPriceAttrResponse interface.
 */
export function instanceOfApartHousingPriceAttrResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApartHousingPriceAttrResponseFromJSON(json: any): ApartHousingPriceAttrResponse {
    return ApartHousingPriceAttrResponseFromJSONTyped(json, false);
}

export function ApartHousingPriceAttrResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartHousingPriceAttrResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apartHousingPrices': !exists(json, 'apartHousingPrices') ? undefined : ApartHousingPriceAttrResponseApartHousingPricesFromJSON(json['apartHousingPrices']),
    };
}

export function ApartHousingPriceAttrResponseToJSON(value?: ApartHousingPriceAttrResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apartHousingPrices': ApartHousingPriceAttrResponseApartHousingPricesToJSON(value.apartHousingPrices),
    };
}

