/* tslint:disable */
/* eslint-disable */
/**
 * 공동주택가격정보서비스
 * 공동주택에 대해 매년 공시기준일(1월1일)에 공시한 공동주택 가격정보의 지리데이터에서 생성된 맵 이미지와 도형 및 속성 값을 포함한 피처 집합을 제공하는 공동주택가격정보서비스
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApartHousingPriceAttr } from './ApartHousingPriceAttr';
import {
    ApartHousingPriceAttrFromJSON,
    ApartHousingPriceAttrFromJSONTyped,
    ApartHousingPriceAttrToJSON,
} from './ApartHousingPriceAttr';

/**
 * 
 * @export
 * @interface ApartHousingPriceAttrResponseApartHousingPricesAllOf
 */
export interface ApartHousingPriceAttrResponseApartHousingPricesAllOf {
    /**
     * 
     * @type {Array<ApartHousingPriceAttr>}
     * @memberof ApartHousingPriceAttrResponseApartHousingPricesAllOf
     */
    field: Array<ApartHousingPriceAttr>;
}

/**
 * Check if a given object implements the ApartHousingPriceAttrResponseApartHousingPricesAllOf interface.
 */
export function instanceOfApartHousingPriceAttrResponseApartHousingPricesAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "field" in value;

    return isInstance;
}

export function ApartHousingPriceAttrResponseApartHousingPricesAllOfFromJSON(json: any): ApartHousingPriceAttrResponseApartHousingPricesAllOf {
    return ApartHousingPriceAttrResponseApartHousingPricesAllOfFromJSONTyped(json, false);
}

export function ApartHousingPriceAttrResponseApartHousingPricesAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartHousingPriceAttrResponseApartHousingPricesAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': ((json['field'] as Array<any>).map(ApartHousingPriceAttrFromJSON)),
    };
}

export function ApartHousingPriceAttrResponseApartHousingPricesAllOfToJSON(value?: ApartHousingPriceAttrResponseApartHousingPricesAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': ((value.field as Array<any>).map(ApartHousingPriceAttrToJSON)),
    };
}

