/* tslint:disable */
/* eslint-disable */
/**
 * 공동주택가격정보서비스
 * 공동주택에 대해 매년 공시기준일(1월1일)에 공시한 공동주택 가격정보의 지리데이터에서 생성된 맵 이미지와 도형 및 속성 값을 포함한 피처 집합을 제공하는 공동주택가격정보서비스
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 한 페이지 결과 수
     * @type {string}
     * @memberof Pagination
     */
    numOfRows: string;
    /**
     * 페이지 번호
     * @type {string}
     * @memberof Pagination
     */
    pageNo: string;
    /**
     * 전체 결과 수
     * @type {string}
     * @memberof Pagination
     */
    totalCount: string;
}

/**
 * Check if a given object implements the Pagination interface.
 */
export function instanceOfPagination(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "numOfRows" in value;
    isInstance = isInstance && "pageNo" in value;
    isInstance = isInstance && "totalCount" in value;

    return isInstance;
}

export function PaginationFromJSON(json: any): Pagination {
    return PaginationFromJSONTyped(json, false);
}

export function PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numOfRows': json['numOfRows'],
        'pageNo': json['pageNo'],
        'totalCount': json['totalCount'],
    };
}

export function PaginationToJSON(value?: Pagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'numOfRows': value.numOfRows,
        'pageNo': value.pageNo,
        'totalCount': value.totalCount,
    };
}

