/* tslint:disable */
/* eslint-disable */
/**
 * 한국수출입은행 오픈 API
 * 한국수출입은행이 보유한 공공데이터를 제공받아 누구나 직접 응용프로그램과 서비스개발 등에 활용할 수 있습니다.
 *
 * The version of the OpenAPI document: 2022.08.10
 * Contact: h.lee@koreaexim.go.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExchangeResponse,
} from '../models';
import {
    ExchangeResponseFromJSON,
    ExchangeResponseToJSON,
} from '../models';

export interface ExchangeRequest {
    data: ExchangeDataEnum;
    searchdate?: Date;
}

/**
 * 
 */
export class ExchangeApi extends runtime.BaseAPI {

    /**
     * 한국수출입은행이 제공하는 환율정보입니다.
     * 
     * # 공지사항
     * - 보다 안정적인 서비스 제공을 위하여, 7월부터 Open API 서비스에 일일 호출 가능 횟수 제한이 적용될 예정입니다. (2020.6.12)
     * 홈페이지 개편으로 인해 IP주소가 변경되었습니다. (2022.4.9)
     * 
     * # 개인정보보유기간 만료에 따른 인증키 파기 처리 관련
     * RESULT 3으로 반환되시는 경우, 최초 신청시 입력해주셨던 개인정보의 보유기간이 만료되어 API 키가 파기되었을 가능성이 높습니다.
     * 한국수출입은행에서 제공하는 OPEN API의 경우 신청시 개인정보를 받고 있어
     * 개인정보보호법에 따라 보유기간(2년)이 지난 사용자의 경우 개인정보 및 사용정보 등이 폐기처리 됩니다.
     * 다만, 보유기간 전 홈페이지에 접속하시어 개인정보 보유 재동의를 해주시면 사용기간이 2년이 연장됩니다.
     * 키 파기 처리전 신청시 등록해주셨던 이메일로 보유기간 만료 예정이며, 재동의를 독려하는 안내메일을 보내드리고 있습니다.
     * 파기된 키의 경우 재사용이 불가함으로 신규 신청부탁드립니다.
     * 
     * # 변경 이력
     * - 일일 호출 가능 횟수를 1000회로 제한 (1000회 이상 호출 시 result:4 반환, 데이터 미제공) / 적용 일시 : 2020. 7. 13(월) 오후 6시
     * - 홈페이지 IP 주소 변경 (211.171.208.5 -> 39.115.136.135) / 적용 일시 : 2022. 4. 11(월) 오전 9시
     * 
     */
    async exchangeRaw(requestParameters: ExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangeResponse>> {
        if (requestParameters.data === null || requestParameters.data === undefined) {
            throw new runtime.RequiredError('data','Required parameter requestParameters.data was null or undefined when calling exchange.');
        }

        const queryParameters: any = {};

        if (requestParameters.searchdate !== undefined) {
            queryParameters['searchdate'] = (requestParameters.searchdate as any).toISOString().substr(0,10);
        }

        if (requestParameters.data !== undefined) {
            queryParameters['data'] = requestParameters.data;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["authkey"] = this.configuration.apiKey("authkey"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/site/program/financial/exchangeJSON`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExchangeResponseFromJSON(jsonValue));
    }

    /**
     * 한국수출입은행이 제공하는 환율정보입니다.
     * 
     * # 공지사항
     * - 보다 안정적인 서비스 제공을 위하여, 7월부터 Open API 서비스에 일일 호출 가능 횟수 제한이 적용될 예정입니다. (2020.6.12)
     * 홈페이지 개편으로 인해 IP주소가 변경되었습니다. (2022.4.9)
     * 
     * # 개인정보보유기간 만료에 따른 인증키 파기 처리 관련
     * RESULT 3으로 반환되시는 경우, 최초 신청시 입력해주셨던 개인정보의 보유기간이 만료되어 API 키가 파기되었을 가능성이 높습니다.
     * 한국수출입은행에서 제공하는 OPEN API의 경우 신청시 개인정보를 받고 있어
     * 개인정보보호법에 따라 보유기간(2년)이 지난 사용자의 경우 개인정보 및 사용정보 등이 폐기처리 됩니다.
     * 다만, 보유기간 전 홈페이지에 접속하시어 개인정보 보유 재동의를 해주시면 사용기간이 2년이 연장됩니다.
     * 키 파기 처리전 신청시 등록해주셨던 이메일로 보유기간 만료 예정이며, 재동의를 독려하는 안내메일을 보내드리고 있습니다.
     * 파기된 키의 경우 재사용이 불가함으로 신규 신청부탁드립니다.
     * 
     * # 변경 이력
     * - 일일 호출 가능 횟수를 1000회로 제한 (1000회 이상 호출 시 result:4 반환, 데이터 미제공) / 적용 일시 : 2020. 7. 13(월) 오후 6시
     * - 홈페이지 IP 주소 변경 (211.171.208.5 -> 39.115.136.135) / 적용 일시 : 2022. 4. 11(월) 오전 9시
     * 
     */
    async exchange(requestParameters: ExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangeResponse> {
        const response = await this.exchangeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ExchangeDataEnum = {
    Ap01: 'AP01'
} as const;
export type ExchangeDataEnum = typeof ExchangeDataEnum[keyof typeof ExchangeDataEnum];
