/* tslint:disable */
/* eslint-disable */
/**
 * 한국수출입은행 오픈 API
 * 한국수출입은행이 보유한 공공데이터를 제공받아 누구나 직접 응용프로그램과 서비스개발 등에 활용할 수 있습니다.
 *
 * The version of the OpenAPI document: 2022.08.10
 * Contact: h.lee@koreaexim.go.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeFailed
 */
export interface ExchangeFailed {
    /**
     * 조회 결과
     * | 결과코드 | 설명 |
     * | --- | --- |
     * | 2 | DATA코드 오류 |
     * | 3 | 인증코드 오류 |
     * | 4 | 일일제한횟수 마감 |
     * @type {number}
     * @memberof ExchangeFailed
     */
    result: ExchangeFailedResultEnum;
    /**
     * 통화코드
     * @type {string}
     * @memberof ExchangeFailed
     */
    curUnit: string | null;
    /**
     * 국가/통화명
     * @type {string}
     * @memberof ExchangeFailed
     */
    curNm: string | null;
    /**
     * 전신환(송금) 받으실때
     * @type {string}
     * @memberof ExchangeFailed
     */
    ttb: string | null;
    /**
     * 전신환(송금) 보내실때
     * @type {string}
     * @memberof ExchangeFailed
     */
    tts: string | null;
    /**
     * 매매 기준율
     * @type {string}
     * @memberof ExchangeFailed
     */
    dealBasR: string | null;
    /**
     * 장부가격
     * @type {string}
     * @memberof ExchangeFailed
     */
    bkpr: string | null;
    /**
     * 년환가료율
     * @type {string}
     * @memberof ExchangeFailed
     */
    yyEfeeR: string | null;
    /**
     * 10일환가료율
     * @type {string}
     * @memberof ExchangeFailed
     */
    tenDdEfeeR: string | null;
    /**
     * 서울외국환중개 매매기준율
     * @type {string}
     * @memberof ExchangeFailed
     */
    kftcDealBasR: string | null;
    /**
     * 서울외국환중개 장부가격
     * @type {string}
     * @memberof ExchangeFailed
     */
    kftcBkpr: string | null;
}

/**
 * 조회 결과
 * | 결과코드 | 설명 |
 * | --- | --- |
 * | 2 | DATA코드 오류 |
 * | 3 | 인증코드 오류 |
 * | 4 | 일일제한횟수 마감 |
 */
export type ExchangeFailedResultEnum =
    2|
    3|
    4

const ExchangeFailedResultEnumValues = [
    2,
    3,
    4,
]

export function isExchangeFailedResultEnum(value: any): value is ExchangeFailedResultEnum {
    return ExchangeFailedResultEnumValues.indexOf(value as unknown as ExchangeFailedResultEnum) !== -1
}



/**
 * Check if a given object implements the ExchangeFailed interface.
 */
export function instanceOfExchangeFailed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "curUnit" in value;
    isInstance = isInstance && "curNm" in value;
    isInstance = isInstance && "ttb" in value;
    isInstance = isInstance && "tts" in value;
    isInstance = isInstance && "dealBasR" in value;
    isInstance = isInstance && "bkpr" in value;
    isInstance = isInstance && "yyEfeeR" in value;
    isInstance = isInstance && "tenDdEfeeR" in value;
    isInstance = isInstance && "kftcDealBasR" in value;
    isInstance = isInstance && "kftcBkpr" in value;

    return isInstance;
}

export function ExchangeFailedFromJSON(json: any): ExchangeFailed {
    return ExchangeFailedFromJSONTyped(json, false);
}

export function ExchangeFailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeFailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!exists(json, 'result')) {
        return json;
    }
    if (
        !isExchangeFailedResultEnum(json['result'])
        && json['result'] !== undefined
    ) {
        return json;
    }
    return {
        
        'result': json['result'],
        'curUnit': json['cur_unit'],
        'curNm': json['cur_nm'],
        'ttb': json['ttb'],
        'tts': json['tts'],
        'dealBasR': json['deal_bas_r'],
        'bkpr': json['bkpr'],
        'yyEfeeR': json['yy_efee_r'],
        'tenDdEfeeR': json['ten_dd_efee_r'],
        'kftcDealBasR': json['kftc_deal_bas_r'],
        'kftcBkpr': json['kftc_bkpr'],
    };
}

export function ExchangeFailedToJSON(value?: ExchangeFailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'cur_unit': value.curUnit,
        'cur_nm': value.curNm,
        'ttb': value.ttb,
        'tts': value.tts,
        'deal_bas_r': value.dealBasR,
        'bkpr': value.bkpr,
        'yy_efee_r': value.yyEfeeR,
        'ten_dd_efee_r': value.tenDdEfeeR,
        'kftc_deal_bas_r': value.kftcDealBasR,
        'kftc_bkpr': value.kftcBkpr,
    };
}

