/* tslint:disable */
/* eslint-disable */
/**
 * 한국수출입은행 오픈 API
 * 한국수출입은행이 보유한 공공데이터를 제공받아 누구나 직접 응용프로그램과 서비스개발 등에 활용할 수 있습니다.
 *
 * The version of the OpenAPI document: 2022.08.10
 * Contact: h.lee@koreaexim.go.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternationalSuccessItem
 */
export interface InternationalSuccessItem {
    /**
     * 조회 결과
     * @type {number}
     * @memberof InternationalSuccessItem
     */
    result: InternationalSuccessItemResultEnum;
    /**
     * 금리 통화 정보
     * @type {string}
     * @memberof InternationalSuccessItem
     */
    curFund: string;
    /**
     * 금리 기간 정보
     * @type {string}
     * @memberof InternationalSuccessItem
     */
    sflnIntrcNm: string;
    /**
     * 금리 정보
     * @type {string}
     * @memberof InternationalSuccessItem
     */
    intR: string;
}


/**
 * @export
 */
export const InternationalSuccessItemResultEnum = {
    NUMBER_1: 1
} as const;
export type InternationalSuccessItemResultEnum = typeof InternationalSuccessItemResultEnum[keyof typeof InternationalSuccessItemResultEnum];


/**
 * Check if a given object implements the InternationalSuccessItem interface.
 */
export function instanceOfInternationalSuccessItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "curFund" in value;
    isInstance = isInstance && "sflnIntrcNm" in value;
    isInstance = isInstance && "intR" in value;

    return isInstance;
}

export function InternationalSuccessItemFromJSON(json: any): InternationalSuccessItem {
    return InternationalSuccessItemFromJSONTyped(json, false);
}

export function InternationalSuccessItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternationalSuccessItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'curFund': json['cur_fund'],
        'sflnIntrcNm': json['sfln_intrc_nm'],
        'intR': json['int_r'],
    };
}

export function InternationalSuccessItemToJSON(value?: InternationalSuccessItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'cur_fund': value.curFund,
        'sfln_intrc_nm': value.sflnIntrcNm,
        'int_r': value.intR,
    };
}

