/* tslint:disable */
/* eslint-disable */
/**
 * 한국수출입은행 오픈 API
 * 한국수출입은행이 보유한 공공데이터를 제공받아 누구나 직접 응용프로그램과 서비스개발 등에 활용할 수 있습니다.
 *
 * The version of the OpenAPI document: 2022.08.10
 * Contact: h.lee@koreaexim.go.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternationalFailed
 */
export interface InternationalFailed {
    /**
     * 조회 결과
     * | 결과코드 | 설명 |
     * | --- | --- |
     * | 2 | DATA코드 오류 |
     * | 3 | 인증코드 오류 |
     * | 4 | 일일제한횟수 마감 |
     * @type {number}
     * @memberof InternationalFailed
     */
    result: InternationalFailedResultEnum;
    /**
     * 금리 통화 정보
     * @type {string}
     * @memberof InternationalFailed
     */
    curFund: string | null;
    /**
     * 금리 기간 정보
     * @type {string}
     * @memberof InternationalFailed
     */
    sflnIntrcNm: string | null;
    /**
     * 금리 정보
     * @type {string}
     * @memberof InternationalFailed
     */
    intR: string | null;
}


/**
 * @export
 */
export const InternationalFailedResultEnum = {
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type InternationalFailedResultEnum = typeof InternationalFailedResultEnum[keyof typeof InternationalFailedResultEnum];


/**
 * Check if a given object implements the InternationalFailed interface.
 */
export function instanceOfInternationalFailed(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "curFund" in value;
    isInstance = isInstance && "sflnIntrcNm" in value;
    isInstance = isInstance && "intR" in value;

    return isInstance;
}

export function InternationalFailedFromJSON(json: any): InternationalFailed {
    return InternationalFailedFromJSONTyped(json, false);
}

export function InternationalFailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternationalFailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
        'curFund': json['cur_fund'],
        'sflnIntrcNm': json['sfln_intrc_nm'],
        'intR': json['int_r'],
    };
}

export function InternationalFailedToJSON(value?: InternationalFailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'cur_fund': value.curFund,
        'sfln_intrc_nm': value.sflnIntrcNm,
        'int_r': value.intR,
    };
}

