/* tslint:disable */
/* eslint-disable */
/**
 * 주소기반산업서비스
 * 행정안전부  [주소기반산업서비스](https://business.juso.go.kr/addrlink/main.do) 에서 제공하는 도로명주소 Open API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddrDetailResponse,
  AddrDetailResults,
} from '../models';
import {
    AddrDetailResponseFromJSON,
    AddrDetailResponseToJSON,
    AddrDetailResultsFromJSON,
    AddrDetailResultsToJSON,
} from '../models';

export interface AddrDetailApiGetRequest {
    /**
     * 행정구역코드
     */
    admCd: string;
    /**
     * 도로명코드
     */
    rnMgtSn: string;
    /**
     * 지하여부
     */
    udrtYn: string;
    /**
     * 건물본번
     */
    buldMnnm: number;
    /**
     * 건물부번
     */
    buldSlno: number;
    /**
     * 검색유형
     */
    searchType: AddrDetailApiGetSearchTypeEnum;
    /**
     * 동 (층호 검색 시 입력)
     */
    dongNm?: string;
    /**
     * 검색결과형식 설정
     */
    resultType?: AddrDetailApiGetResultTypeEnum;
}

export interface AddrDetailApiPostRequest {
    /**
     * 행정구역코드
     */
    admCd: string;
    /**
     * 도로명코드
     */
    rnMgtSn: string;
    /**
     * 지하여부
     */
    udrtYn: string;
    /**
     * 건물본번
     */
    buldMnnm: number;
    /**
     * 건물부번
     */
    buldSlno: number;
    /**
     * 검색유형
     */
    searchType: AddrDetailApiPostSearchTypeEnum;
    /**
     * 동 (층호 검색 시 입력)
     */
    dongNm?: string;
    /**
     * 검색결과형식 설정
     */
    resultType?: AddrDetailApiPostResultTypeEnum;
}

/**
 * 
 */
export class DetailApi extends runtime.BaseAPI {

    /**
     * 상세주소 검색
     * 
     */
    async addrDetailApiGetRaw(requestParameters: AddrDetailApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddrDetailResponse>> {
        if (requestParameters.admCd === null || requestParameters.admCd === undefined) {
            throw new runtime.RequiredError('admCd','Required parameter requestParameters.admCd was null or undefined when calling addrDetailApiGet.');
        }

        if (requestParameters.rnMgtSn === null || requestParameters.rnMgtSn === undefined) {
            throw new runtime.RequiredError('rnMgtSn','Required parameter requestParameters.rnMgtSn was null or undefined when calling addrDetailApiGet.');
        }

        if (requestParameters.udrtYn === null || requestParameters.udrtYn === undefined) {
            throw new runtime.RequiredError('udrtYn','Required parameter requestParameters.udrtYn was null or undefined when calling addrDetailApiGet.');
        }

        if (requestParameters.buldMnnm === null || requestParameters.buldMnnm === undefined) {
            throw new runtime.RequiredError('buldMnnm','Required parameter requestParameters.buldMnnm was null or undefined when calling addrDetailApiGet.');
        }

        if (requestParameters.buldSlno === null || requestParameters.buldSlno === undefined) {
            throw new runtime.RequiredError('buldSlno','Required parameter requestParameters.buldSlno was null or undefined when calling addrDetailApiGet.');
        }

        if (requestParameters.searchType === null || requestParameters.searchType === undefined) {
            throw new runtime.RequiredError('searchType','Required parameter requestParameters.searchType was null or undefined when calling addrDetailApiGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.admCd !== undefined) {
            queryParameters['admCd'] = requestParameters.admCd;
        }

        if (requestParameters.rnMgtSn !== undefined) {
            queryParameters['rnMgtSn'] = requestParameters.rnMgtSn;
        }

        if (requestParameters.udrtYn !== undefined) {
            queryParameters['udrtYn'] = requestParameters.udrtYn;
        }

        if (requestParameters.buldMnnm !== undefined) {
            queryParameters['buldMnnm'] = requestParameters.buldMnnm;
        }

        if (requestParameters.buldSlno !== undefined) {
            queryParameters['buldSlno'] = requestParameters.buldSlno;
        }

        if (requestParameters.searchType !== undefined) {
            queryParameters['searchType'] = requestParameters.searchType;
        }

        if (requestParameters.dongNm !== undefined) {
            queryParameters['dongNm'] = requestParameters.dongNm;
        }

        if (requestParameters.resultType !== undefined) {
            queryParameters['resultType'] = requestParameters.resultType;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["confmKey"] = this.configuration.apiKey("confmKey"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/addrlink/addrDetailApi.do`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddrDetailResponseFromJSON(jsonValue));
    }

    /**
     * 상세주소 검색
     * 
     */
    async addrDetailApiGet(requestParameters: AddrDetailApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddrDetailResponse> {
        const response = await this.addrDetailApiGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 상세주소 검색
     * 
     */
    async addrDetailApiPostRaw(requestParameters: AddrDetailApiPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddrDetailResponse>> {
        if (requestParameters.admCd === null || requestParameters.admCd === undefined) {
            throw new runtime.RequiredError('admCd','Required parameter requestParameters.admCd was null or undefined when calling addrDetailApiPost.');
        }

        if (requestParameters.rnMgtSn === null || requestParameters.rnMgtSn === undefined) {
            throw new runtime.RequiredError('rnMgtSn','Required parameter requestParameters.rnMgtSn was null or undefined when calling addrDetailApiPost.');
        }

        if (requestParameters.udrtYn === null || requestParameters.udrtYn === undefined) {
            throw new runtime.RequiredError('udrtYn','Required parameter requestParameters.udrtYn was null or undefined when calling addrDetailApiPost.');
        }

        if (requestParameters.buldMnnm === null || requestParameters.buldMnnm === undefined) {
            throw new runtime.RequiredError('buldMnnm','Required parameter requestParameters.buldMnnm was null or undefined when calling addrDetailApiPost.');
        }

        if (requestParameters.buldSlno === null || requestParameters.buldSlno === undefined) {
            throw new runtime.RequiredError('buldSlno','Required parameter requestParameters.buldSlno was null or undefined when calling addrDetailApiPost.');
        }

        if (requestParameters.searchType === null || requestParameters.searchType === undefined) {
            throw new runtime.RequiredError('searchType','Required parameter requestParameters.searchType was null or undefined when calling addrDetailApiPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.admCd !== undefined) {
            queryParameters['admCd'] = requestParameters.admCd;
        }

        if (requestParameters.rnMgtSn !== undefined) {
            queryParameters['rnMgtSn'] = requestParameters.rnMgtSn;
        }

        if (requestParameters.udrtYn !== undefined) {
            queryParameters['udrtYn'] = requestParameters.udrtYn;
        }

        if (requestParameters.buldMnnm !== undefined) {
            queryParameters['buldMnnm'] = requestParameters.buldMnnm;
        }

        if (requestParameters.buldSlno !== undefined) {
            queryParameters['buldSlno'] = requestParameters.buldSlno;
        }

        if (requestParameters.searchType !== undefined) {
            queryParameters['searchType'] = requestParameters.searchType;
        }

        if (requestParameters.dongNm !== undefined) {
            queryParameters['dongNm'] = requestParameters.dongNm;
        }

        if (requestParameters.resultType !== undefined) {
            queryParameters['resultType'] = requestParameters.resultType;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["confmKey"] = this.configuration.apiKey("confmKey"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/addrlink/addrDetailApi.do`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddrDetailResponseFromJSON(jsonValue));
    }

    /**
     * 상세주소 검색
     * 
     */
    async addrDetailApiPost(requestParameters: AddrDetailApiPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddrDetailResponse> {
        const response = await this.addrDetailApiPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AddrDetailApiGetSearchTypeEnum = {
    Dong: 'dong',
    Floorho: 'floorho'
} as const;
export type AddrDetailApiGetSearchTypeEnum = typeof AddrDetailApiGetSearchTypeEnum[keyof typeof AddrDetailApiGetSearchTypeEnum];
/**
 * @export
 */
export const AddrDetailApiGetResultTypeEnum = {
    Xml: 'xml',
    Json: 'json'
} as const;
export type AddrDetailApiGetResultTypeEnum = typeof AddrDetailApiGetResultTypeEnum[keyof typeof AddrDetailApiGetResultTypeEnum];
/**
 * @export
 */
export const AddrDetailApiPostSearchTypeEnum = {
    Dong: 'dong',
    Floorho: 'floorho'
} as const;
export type AddrDetailApiPostSearchTypeEnum = typeof AddrDetailApiPostSearchTypeEnum[keyof typeof AddrDetailApiPostSearchTypeEnum];
/**
 * @export
 */
export const AddrDetailApiPostResultTypeEnum = {
    Xml: 'xml',
    Json: 'json'
} as const;
export type AddrDetailApiPostResultTypeEnum = typeof AddrDetailApiPostResultTypeEnum[keyof typeof AddrDetailApiPostResultTypeEnum];
